// @generated by `cargo xtask codegen` — DO NOT EDIT.
//
// Rust definitions of the kernel structs the eBPF programs read via CO-RE (e.g. `task_struct`).
// Regenerate with `cargo xtask codegen`, which runs `aya-tool generate` against the host's BTF
// (`/sys/kernel/btf/vmlinux`). aya relocates field offsets at *load* time against the target
// kernel's BTF, so this file — generated on one kernel — stays portable across kernels.
//
// This is a placeholder until `cargo xtask codegen` is run (it needs `bpftool` + `aya-tool`).
#![allow(
    non_camel_case_types,
    non_snake_case,
    non_upper_case_globals,
    dead_code,
    clippy::all
)]
