//! `cargo xtask` — build/run orchestration for the agent.
//!
//! `build` compiles the agent (its build.rs cross-compiles + embeds the eBPF object under nightly).
//! `run` builds then launches the agent under `sudo`, since loading eBPF needs CAP_BPF/CAP_PERFMON.

use std::process::{Command, Stdio};

use clap::{Parser, Subcommand};

/// Kernel structs to generate CO-RE bindings for. `task_struct` transitively pulls in the nested
/// types M1 needs (nsproxy → mnt_namespace → ns_common). Append new structs as later probes need
/// them (e.g. `sock` in M3), then re-run `cargo xtask codegen`.
const VMLINUX_TYPES: &[&str] = &["task_struct"];

/// Where the generated bindings are written (committed; regenerate via `cargo xtask codegen`).
const VMLINUX_PATH: &str = "crates/ebpf/src/vmlinux.rs";

#[derive(Parser)]
#[command(name = "xtask", about = "build orchestration for the agent")]
struct Cli {
    #[command(subcommand)]
    cmd: Cmd,
}

#[derive(Subcommand)]
enum Cmd {
    /// Build the agent (compiles + embeds the eBPF object).
    Build {
        /// Build the release profile.
        #[arg(long)]
        release: bool,
    },
    /// Build, then run the agent under sudo (eBPF load needs elevated capabilities).
    Run {
        /// Build the release profile.
        #[arg(long)]
        release: bool,
        /// Arguments forwarded to the agent binary (e.g. `-- --once`).
        #[arg(last = true)]
        args: Vec<String>,
    },
    /// Regenerate CO-RE kernel-struct bindings (`crates/ebpf/src/vmlinux.rs`) from host BTF.
    /// Requires `aya-tool` + `bpftool`.
    Codegen,
}

fn main() -> anyhow::Result<()> {
    match Cli::parse().cmd {
        Cmd::Build { release } => build(release),
        Cmd::Run { release, args } => {
            build(release)?;
            let bin = format!("target/{}/agent", if release { "release" } else { "debug" });
            run_as_root(&bin, &args)
        }
        Cmd::Codegen => codegen(),
    }
}

fn build(release: bool) -> anyhow::Result<()> {
    let mut args = vec!["build", "-p", "agent"];
    if release {
        args.push("--release");
    }
    cargo(&args)
}

fn cargo(args: &[&str]) -> anyhow::Result<()> {
    let status = Command::new("cargo").args(args).status()?;
    anyhow::ensure!(status.success(), "`cargo {}` failed", args.join(" "));
    Ok(())
}

fn run_as_root(bin: &str, args: &[String]) -> anyhow::Result<()> {
    let status = Command::new("sudo").arg(bin).args(args).status()?;
    anyhow::ensure!(status.success(), "agent exited unsuccessfully ({status})");
    Ok(())
}

/// Regenerate `crates/ebpf/src/vmlinux.rs` from the host's BTF via `aya-tool`.
fn codegen() -> anyhow::Result<()> {
    for tool in ["aya-tool", "bpftool"] {
        anyhow::ensure!(
            on_path(tool),
            "`{tool}` not found on PATH — CO-RE codegen needs both `aya-tool` and `bpftool`.\n\
             Install:\n  \
             bpftool (Arch):   sudo pacman -S bpf\n  \
             bindgen:          cargo install bindgen-cli\n  \
             aya-tool:         cargo install --git https://github.com/aya-rs/aya -- aya-tool"
        );
    }

    let out = Command::new("aya-tool")
        .arg("generate")
        .args(VMLINUX_TYPES)
        .output()?;
    anyhow::ensure!(
        out.status.success(),
        "`aya-tool generate` failed:\n{}",
        String::from_utf8_lossy(&out.stderr)
    );

    let header = format!(
        "// @generated by `cargo xtask codegen` — DO NOT EDIT.\n\
         //\n\
         // CO-RE bindings ({}); field offsets are relocated at load time against the target\n\
         // kernel's BTF, so this file stays portable. Regenerate with `cargo xtask codegen`.\n\
         #![allow(non_camel_case_types, non_snake_case, non_upper_case_globals, dead_code, clippy::all)]\n\n",
        VMLINUX_TYPES.join(", ")
    );

    let mut contents = header.into_bytes();
    contents.extend_from_slice(&out.stdout);
    std::fs::write(VMLINUX_PATH, contents)?;
    println!("wrote {VMLINUX_PATH} ({} type(s))", VMLINUX_TYPES.len());
    Ok(())
}

/// True if `tool` can be spawned from PATH (exit code irrelevant).
fn on_path(tool: &str) -> bool {
    Command::new(tool)
        .arg("--help")
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()
        .is_ok()
}
